family_album/family_album/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('images.urls', namespace='images')),
    path('signup/', include('signups.urls', namespace='signups')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

family_album/images/urls.py
from django.urls import path

from . import views

app_name = 'images'

urlpatterns = [
    path('', views.index, name='home'),
    path('<int:user_id>/', views.index, name='home'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail')

]

family_album/signups/urls.py
from django.urls import path

from . import views

app_name = 'signups'

urlpatterns = [
    path('signup/', views.Signup.as_view(),name='signup'),

]

family_album/images/models.py
from django.utils import timezone
from PIL import Image as img
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    image = models.ImageField(upload_to='pictures')
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created_at',)

    def save(self):
        # Opening the uploaded image
        im = img.open(self.image)
        output = BytesIO()
        # Resize/modify the image
        im = im.resize((400, 300))

        # after modifications, save it to the output
        im.save(output, format='JPEG', quality=100)
        output.seek(0)

        # change the imagefield value to be the newley modifed image value
        self.image = InMemoryUploadedFile(
            output, 'ImageField',
            "%s.jpeg" % self.image.name.split('.')[0],
            'jpeg', sys.getsizeof(output), None
        )
        super(Image, self).save()

    def __str__(self):
        return self.description

family_album/signups/models.py
from django.db import models

# Create your models here.

family_album/images/forms.py
from django.forms import ModelForm
from .models import Image


class UploadForm(ModelForm):
    class Meta:
        model = Image
        fields = ['description', 'image']

family_album/images/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.views.generic.edit import DeleteView
from django.views.generic import DetailView
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from .forms import UploadForm
from .models import Image
import os


def index(request, user_id=None):
    if user_id:
        images = Image.objects.filter(user_id=user_id)
    else:
        images = Image.objects.all()
    # Show 8 contacts per page
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images = paginator.get_page(page)
    return render(request, 'index.html', {'images': images})


class UploadView(LoginRequiredMixin, FormView):
    template_name = 'images/upload.html'
    form_class = UploadForm
    success_url = reverse_lazy('images:home')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class DeleteView(DeleteView):
    template_name = 'images/delete.html'
    model = Image
    success_url = reverse_lazy('images:home')

    def get_object(self, queryset=None):
        obj = super(DeleteView, self).get_object()
        path = obj.image.url
        if os.path.exists(path):
            os.remove(path)
        return obj


class DetailView(DetailView):
    context_object_name = 'image'
    queryset = Image.objects.all()
    template_name = 'images/detail.html'

family_album/signups/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views import generic


class Signup(generic.CreateView):
    form_class = UserCreationForm
    success_url = '/accounts/login'
    template_name = 'registration/register.html'

family_album/images/templates/images/delete.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
<div class="login-form">
    <form method="POST">
        {% csrf_token %}
        <h2> Please confirm below!</h2>
        <p>Are you sure you want to delete this image ?</p>
        <input type="submit" value="Confirm" class="btn btn-default btn-lg">
    </form>
</div>
{% endblock %}

family_album/images/templates/images/detail.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <br>
        <div class="card" style="width:60%;">
          <img class="card-img-top" src="{{image.image.url}}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Uploaded on {{image.created_at}} by {{image.user}}</h5>
            <p class="card-text">{{image.description}}</p>
            {% if user.is_authenticated and user == image.user%}
                <a href="{% url 'images:delete' pk=image.id %}" class="btn btn-default">Delete Image</a>
            {% endif %}
          </div>
        </div>
    </div>
</div>
{% endblock %}

family_album/images/templates/images/upload.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}
{% block content %}
<div class="login-form">
    <h2>Upload your image </h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|bootstrap}}
        <input type="submit" value="upload " id="upload" class="btn btn-default btn-lg">
    </form>
    <img id="loader" src="{% static 'img/ajaxloader.gif'%}">
</div>
{% endblock %}

family_album/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My Family Album</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Playfair+Display" rel="stylesheet">


    <!-- Bootstrap core CSS -->

    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/thumbnail-gallery.css" %}" rel="stylesheet">
    <link href="{% static "css/mystyles.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'images:home' %}">Family Album</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'images:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'images:upload' %}">Upload a Image
                <span class="sr-only"></span>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'images:home' user_id=user.id %}">Your Images
                <span class="sr-only"></span>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/accounts/logout">Logout
                <span class="sr-only"></span>
              </a>
            </li>
            {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="/accounts/login">Login
                    <span class="sr-only"></span>
                  </a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'signups:signup' %}">Create a account
                    <span class="sr-only"></span>
                  </a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content%}
        {% endblock %}

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 footer">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; familyAlbum 2019</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "vendor/script.js" %}"></script>

  </body>

</html>

family_album/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="my-4 text-center text-lg-left">Memorable Pictures</h1>
<div class="row">
    <div class="col-sm-12">
        {% if images %}
        <div class="pagination">
            <span class="step-links">
                {% if images.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ images.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ images.number }} of {{ images.paginator.num_pages }}.
                </span>

                {% if images.has_next %}
                    <a href="?page={{ images.next_page_number }}">next</a>
                    <a href="?page={{ images.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
</div>
<div class="row text-center text-lg-left image-container">
    {% if images %}
        {% for image in images %}
            <div class="col-lg-3 col-md-4 col-xs-6">
              <a href="{% url 'images:detail' pk=image.id%}" class="d-block mb-4 h-100 image">
                <img class="img-fluid img-thumbnail" src="{{image.image.url}}" alt="">
                <p class="desc">{{image.description}}</p>
                <p>Uploaded by: {{image.user}}</p>
              </a>
            </div>
        {% endfor %}
    {% else %}
        <div class="col-lg-3 col-md-4 col-xs-6">
          <h3>No images uploaded yet !</h3>
        </div>
    {% endif %}

</div>

{% endblock %}